name = "Griddle"
uuid = "adcba3db-3c53-44d1-b103-103496a1f186"
authors = ["Mark Baum"]
version = "1.0.0-DEV"

[compat]
julia = "1.3"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
